language: go
go:
  - 1.9.2
before_install:
  - go get -t -v ./...
script:
  - ./test.sh
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash)